version: '3'

services:
    ds-redis:
        image: redis:7
        container_name: ds-redis
        hostname: ds-redis
        restart: always
        ports:
        - $REDIS_PORT:$REDIS_PORT
        volumes:
        - redis-cache:/data
        networks:
        - ds-network

    ds-api:
        container_name: ds-api
        hostname: ds-api
        build:
            context: .
        working_dir: /app
        command: /app/ds-api-venv/bin/gunicorn --reload --bind $API_HOST:$API_PORT server:app
        tty: true
        env_file: .env
        environment:
        - PYTHONPATH=/app/src
        ports:
        - $API_PORT:$API_PORT
        volumes:
        - .:/app:delegated
        - home:/home/$LOCAL_USER_NAME
        networks:
        - ds-network

volumes:
    redis-cache:
    home:

networks:
    ds-network:
